/*!
 * -------------------------------------------
 * Copyright (c) 2019, Horizon Robotics, Inc.
 * All rights reserved.
 * \File     gtest_helper.h
 * \Author   Yingmin Li
 * \Mail     yingmin.li@horizon.ai
 * \Version  1.0.0.0
 * \Date     2019-04-15
 * \Brief    implement of gtest_helper.h
 * \DO NOT MODIFY THIS COMMENT, \
 * \WHICH IS AUTO GENERATED BY EDITOR
 * -------------------------------------------
 */
#ifndef TEST_GTEST_HELPER_H_
#define TEST_GTEST_HELPER_H_
#include <string>
#include <unordered_map>
std::unordered_map<std::string, std::string> MYTESTPARAM;
std::unordered_map<std::string, std::string> FilterOwnTestParam(int argc,
                                                                char **argv) {
  std::unordered_map<std::string, std::string> param_map{};
  for (int i = 0; i < argc; ++i) {
    std::string arg_str = argv[i];
    if (arg_str.find("--test_") != std::string::npos) {
      auto pos = arg_str.find_first_of('=');
      std::string param_name(arg_str.begin() + 7, arg_str.begin() + pos);
      param_map[param_name] =
          std::string(arg_str.begin() + pos + 1, arg_str.end());
    }
  }
  return param_map;
}
#endif  // TEST_GTEST_HELPER_H_
