#ifndef VIDEO_SOURCE_VERSION_H_
#define VIDEO_SOURCE_VERSION_H_

#define VIDEO_SOURCE_VERSION "1.0.15"
#define VIDEO_SOURCE_VERSION_TIME \
        VIDEO_SOURCE_VERSION  " " __TIMESTAMP__

#endif  // VIDEO_SOURCE_VERSION_H_
