metadata:
  labels:
    some-label: some-label-value
    class: KubernetesDeclarativeAgentTest
spec:
  containers:
    - name: build
      image: hub.hobot.cc/aiot/hbcc/ubuntu16.04:latest
      command:
      - cat
      tty: true
      env:
        - name: CONTAINER_ENV_VAR
          value: build
