/***************************************************************************
 * COPYRIGHT NOTICE
 * Copyright 2021 Horizon Robotics, Inc.
 * All rights reserved.
 ***************************************************************************/
#ifndef VIDEO_SOURCE_MIPI_CAM_VIN_PARAMS_
#define VIDEO_SOURCE_MIPI_CAM_VIN_PARAMS_
#include <string.h>
#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
#include "vio/hb_mipi_api.h"
#include "vio/hb_vin_api.h"
#ifdef __cplusplus
}
#endif  /* __cplusplus */

namespace videosource {

/* 1. mipi sensor config */
extern MIPI_SENSOR_INFO_S SENSOR_TESTPATTERN_INFO;
extern MIPI_SENSOR_INFO_S SENSOR_4LANE_IMX327_30FPS_12BIT_LINEAR_INFO;
extern MIPI_SENSOR_INFO_S SENSOR_4LANE_IMX327_30FPS_12BIT_DOL2_INFO;
extern MIPI_SENSOR_INFO_S SENSOR_OS8A10_30FPS_10BIT_LINEAR_INFO;
extern MIPI_SENSOR_INFO_S SENSOR_OS8A10_30FPS_10BIT_DOL2_INFO;
extern MIPI_SENSOR_INFO_S SENSOR_4LANE_AR0233_30FPS_12BIT_1080P_954_INFO;
extern MIPI_SENSOR_INFO_S SENSOR_4LANE_AR0233_30FPS_12BIT_1080P_960_INFO;
extern MIPI_SENSOR_INFO_S SENSOR_2LANE_OV10635_30FPS_YUV_720P_954_INFO;
extern MIPI_SENSOR_INFO_S SENSOR_2LANE_OV10635_30FPS_YUV_720P_960_INFO;
extern MIPI_SENSOR_INFO_S SENSOR_S5KGM1SP_30FPS_10BIT_LINEAR_INFO;
extern MIPI_SENSOR_INFO_S SENSOR_F37_30FPS_10BIT_LINEAR_INFO;
extern MIPI_SENSOR_INFO_S SENSOR_SC8238_30FPS_10BIT_LINEAR_INFO;
extern MIPI_SENSOR_INFO_S SENSOR_SC8238_30FPS_10BIT_DOL2_INFO;
extern MIPI_SENSOR_INFO_S SENSOR_IMX586_30FPS_10BIT_LINEAR_INFO;
extern MIPI_SENSOR_INFO_S SENSOR_IMX586_30FPS_10BIT_DOL2_INFO;

/* 2. mipi attr config */
extern MIPI_ATTR_S MIPI_4LANE_SENSOR_IMX327_30FPS_12BIT_NORMAL_SENSOR_CLK_ATTR;
extern MIPI_ATTR_S MIPI_4LANE_SENSOR_IMX327_30FPS_12BIT_DOL2_ATTR;
extern MIPI_ATTR_S MIPI_4LANE_SENSOR_IMX327_30FPS_12BIT_NORMAL_ATTR;
extern MIPI_ATTR_S MIPI_SENSOR_OS8A10_30FPS_10BIT_LINEAR_ATTR;
extern MIPI_ATTR_S MIPI_SENSOR_OS8A10_30FPS_10BIT_LINEAR_SENSOR_CLK_ATTR;
extern MIPI_ATTR_S MIPI_SENSOR_OS8A10_30FPS_10BIT_DOL2_ATTR;
extern MIPI_ATTR_S MIPI_4LANE_SENSOR_AR0233_30FPS_12BIT_1080P_954_ATTR;
extern MIPI_ATTR_S MIPI_4LANE_SENSOR_AR0233_30FPS_12BIT_1080P_960_ATTR;
extern MIPI_ATTR_S MIPI_2LANE_OV10635_30FPS_YUV_720P_954_ATTR;
extern MIPI_ATTR_S MIPI_2LANE_OV10635_30FPS_YUV_720P_960_ATTR;
extern MIPI_ATTR_S MIPI_2LANE_OV10635_30FPS_YUV_LINE_CONCATE_720P_960_ATTR;
extern MIPI_ATTR_S MIPI_SENSOR_S5KGM1SP_30FPS_10BIT_LINEAR_ATTR;
extern MIPI_ATTR_S MIPI_SENSOR_F37_30FPS_10BIT_LINEAR_ATTR;
extern MIPI_ATTR_S MIPI_SENSOR_F37_30FPS_10BIT_LINEAR_SENSOR_CLK_ATTR;
extern MIPI_ATTR_S MIPI_SENSOR_SC8238_30FPS_10BIT_LINEAR_ATTR;
extern MIPI_ATTR_S MIPI_SENSOR_SC8238_30FPS_10BIT_LINEAR_SENSOR_CLK_ATTR;
extern MIPI_ATTR_S MIPI_SENSOR_SC8238_30FPS_10BIT_DOL2_ATTR;
extern MIPI_ATTR_S MIPI_SENSOR_IMX586_30FPS_10BIT_LINEAR_ATTR;
extern MIPI_ATTR_S MIPI_SENSOR_IMX586_30FPS_10BIT_LINEAR_SENSOR_CLK_ATTR;
extern MIPI_ATTR_S MIPI_SENSOR_IMX586_30FPS_10BIT_DOL2_ATTR;
extern MIPI_ATTR_S MIPI_SENSOR_IMX586_30FPS_10BIT_DOL2_SENSOR_CLK_ATTR;

/* 3. vin dev attr config */
extern VIN_DEV_ATTR_S DEV_ATTR_TEST_PATTERN_YUV422_BASE;
extern VIN_DEV_ATTR_S DEV_ATTR_TEST_PATTERN_1080P_BASE;
extern VIN_DEV_ATTR_S DEV_ATTR_TEST_PATTERN_4K_BASE;
extern VIN_DEV_ATTR_S DEV_ATTR_TEST_PATTERN_12M_BASE;
extern VIN_DEV_ATTR_S DEV_ATTR_IMX327_LINEAR_BASE;
extern VIN_DEV_ATTR_S DEV_ATTR_IMX327_DOL2_BASE;
extern VIN_DEV_ATTR_S DEV_ATTR_OS8A10_LINEAR_BASE;
extern VIN_DEV_ATTR_S DEV_ATTR_OS8A10_DOL2_BASE;
extern VIN_DEV_ATTR_S DEV_ATTR_AR0233_1080P_BASE;
extern VIN_DEV_ATTR_S DEV_ATTR_OV10635_YUV_BASE;
extern VIN_DEV_ATTR_S DEV_ATTR_OV10635_YUV_LINE_CONCATE_BASE;
extern VIN_DEV_ATTR_S DEV_ATTR_S5KGM1SP_LINEAR_BASE;
extern VIN_DEV_ATTR_S DEV_ATTR_FEED_BACK_1097P_BASE;
extern VIN_DEV_ATTR_S DEV_ATTR_F37_LINEAR_BASE;
extern VIN_DEV_ATTR_S DEV_ATTR_SC8238_LINEAR_BASE;
extern VIN_DEV_ATTR_S DEV_ATTR_IMX586_LINEAR_BASE;
extern VIN_DEV_ATTR_S DEV_ATTR_IMX586_DOL2_BASE;

/* 4. vin dev attr external config */
extern VIN_DEV_ATTR_EX_S DEV_ATTR_IMX327_MD_BASE;
extern VIN_DEV_ATTR_EX_S DEV_ATTR_OV10635_MD_BASE;

/* 5. vin pipe attr config */
extern VIN_PIPE_ATTR_S PIPE_ATTR_TEST_PATTERN_1080P_BASE;
extern VIN_PIPE_ATTR_S PIPE_ATTR_TEST_PATTERN_12M_BASE;
extern VIN_PIPE_ATTR_S PIPE_ATTR_TEST_PATTERN_4K_BASE;
extern VIN_PIPE_ATTR_S PIPE_ATTR_IMX327_LINEAR_BASE;
extern VIN_PIPE_ATTR_S PIPE_ATTR_IMX327_DOL2_BASE;
extern VIN_PIPE_ATTR_S PIPE_ATTR_OS8A10_LINEAR_BASE;
extern VIN_PIPE_ATTR_S PIPE_ATTR_OS8A10_DOL2_BASE;
extern VIN_PIPE_ATTR_S PIPE_ATTR_AR0233_1080P_BASE;
extern VIN_PIPE_ATTR_S PIPE_ATTR_OV10635_YUV_BASE;
extern VIN_PIPE_ATTR_S VIN_ATTR_OV10635_YUV_LINE_CONCATE_BASE;
extern VIN_PIPE_ATTR_S PIPE_ATTR_S5KGM1SP_LINEAR_BASE;
extern VIN_PIPE_ATTR_S PIPE_ATTR_F37_LINEAR_BASE;
extern VIN_PIPE_ATTR_S PIPE_ATTR_SC8238_LINEAR_BASE;
extern VIN_PIPE_ATTR_S PIPE_ATTR_IMX586_LINEAR_BASE;
extern VIN_PIPE_ATTR_S PIPE_ATTR_IMX586_DOL2_BASE;

/* 6. vin dis attr config */
extern VIN_DIS_ATTR_S DIS_ATTR_BASE;
extern VIN_DIS_ATTR_S DIS_ATTR_12M_BASE;
extern VIN_DIS_ATTR_S DIS_ATTR_OS8A10_BASE;
extern VIN_DIS_ATTR_S DIS_ATTR_OV10635_BASE;
extern VIN_DIS_ATTR_S DIS_ATTR_SC8238_BASE;
extern VIN_DIS_ATTR_S DIS_ATTR_IMX586_BASE;
extern VIN_DIS_ATTR_S DIS_ATTR_F37_BASE;

/* 7. vin ldc attr config */
extern VIN_LDC_ATTR_S LDC_ATTR_12M_BASE;
extern VIN_LDC_ATTR_S LDC_ATTR_BASE;
extern VIN_LDC_ATTR_S LDC_ATTR_OS8A10_BASE;
extern VIN_LDC_ATTR_S LDC_ATTR_OV10635_BASE;
extern VIN_LDC_ATTR_S LDC_ATTR_SC8238_BASE;
extern VIN_LDC_ATTR_S LDC_ATTR_IMX586_BASE;
extern VIN_LDC_ATTR_S LDC_ATTR_F37_BASE;

}  // namespace videosource
#endif  // VIDEO_SOURCE_MIPI_CAM_VIN_PARAMS_
